### ISSUE TITLE
Config should be versioned

### ISSUE THREAD

**Issue by ironcladlou** [openshift/monitor-project-lifecycle#23]
The config type needs to be versioned using the standard apimachinery.

**Comment by joelsmith** [comment]
@ironcladlou I'm not very familiar with the workings of apimachinery. I'm happy to go off and figure it out, but if somebody could provide me with a 60-second overview, I expect we'd be much more likely to get it right. Do we just invent an API object out of thin air and start using it? Do we just add tags to our existing config and object so that it looks like an API object? Do we need to register the object name somewhere and define its schema? 

Are we talking about something like this?

```
apiVersion: v1
kind: MonitorProjectLifecycleAppConfig
```

**Comment by ironcladlou** [comment]
Example: https://github.com/openshift/autoheal/tree/master/pkg/apis/autoheal/v1alpha2

We wouldn't be registering a new API group in OpenShift, just using the machinery to get versioning, conversion, defaulting, validation, etc "for free".

**Comment by ironcladlou** [comment]
I also consider this relatively low priority right now
